---
apiVersion: v1
kind: Pod
metadata:
  name: tkgconfig
spec:
  containers:
  - image: [IMAGE_REGISTRY_GOES_HERE]/clusterconfig:v1
    name: clusterconfig
    command: [ "/bin/bash", "-c", "--"]
    args: ["/clusterconfig.sh -n utility -g utilitycluster -r
    containerd"] #-n == supervisor namespace, -g guestcluster
    volumeMounts:
      - name: tanzuconfigs
        mountPath: "/tanzuconfigs"
  initContainers:
  - image: [IMAGE_REGISTRY_GOES_HERE]/vlogins:v1
    name: login
    command: [ "/bin/bash", "-c", "--"]
    args: ["/newlogin.sh -s sup.hollow.local -u tanzu -p Test123 -n utility -c
    utilitycluster"] # -s supervisorendpoint, -u user, -p pass -n namespace -c cluster
    volumeMounts:
      - name: tanzuconfigs
        mountPath: "/tanzuconfigs"
  volumes:
    - name: tanzuconfigs
      emptyDir: {}